### ISSUE TITLE
Definir API Discord a ser utilizada no Bot

### ISSUE THREAD

**Issue by luigieai** [Techbox-Project/techbox#1]
Olá!
Qual Wrapper devemos utilizar para nos comunicarmos com o Discord? Alguém tem alguma sugestão?

Ao postar a API, por favor certifique-se de:
* Postar um link para a API
* API seja bem documentada
* Preferencialmente um motivo para utilizarmos ela

Grato!

Ao ser definido, devemos adicionar a Task de implementação dessa API (por exemplo, definir o repo dela no Gradle) nas tasks do Projeto

**Comment by DevNatan** [comment]
Kotlin + Coroutines = melhor bot ja feito na existência
~~não procurei wrapper~~

**Comment by zMigueel** [comment]
Caso o projeto centralize-se ao Kotlin, temos o Kord como API, ou pode usar o JDA mesmo

https://github.com/kordlib/kord
https://github.com/DV8FromTheWorld/JDA

**Comment by luigieai** [comment]
Aparentemente o JDA é um projeto mais maturo que o Kord, não vejo problemas em utilizar Kotlin com ele, e acho que teremos mais estabilidade a longo prazo.

**Comment by LorenzooG** [comment]
> Aparentemente o JDA é um projeto mais maturo que o Kord, não vejo problemas em utilizar Kotlin com ele, e acho que teremos mais estabilidade a longo prazo.

Eu acho que o JDA não é tão bom com Kotlin, porque há várias coisas como coroutines, etc, que não são suportadas por padrão. Claro que ser mais maduro que o Kord é um bom ponto, mas é um wrapper de discord em desenvolvimento, creio que o suporte seria mais rápido e eficiente, além de já possuir suporte para coroutines por exemplo.

**Comment by luiz-otavio** [comment]
Podemos procurar mais dentro desse artigo publicado pelo Discord: https://discord.com/developers/docs/topics/community-resources

Alguns usuários recomendaram o uso do Catnip (https://github.com/mewna/catnip), para que possamos usar Kotlin nesse projeto.

Catnip há documentações e canais de suporte dentro de seu grupo. (https://discord.gg/yeF2HpP)

**Comment by mtbarr** [comment]
Olá novamente! 

Atualmente decidimos que vamos utilizar JDA (https://github.com/DV8FromTheWorld/JDA) por sua estabilidade e varios bugs já resolvidos. Alem de que nossos desenvolvedores já possui certa experiência com a framework.
