### ISSUE TITLE
Definir API de testes

### ISSUE THREAD

**Issue by luigieai** [Techbox-Project/techbox#2]
Olá!

Para todo projeto, é essencial termos testes para garantir integridade do código e facilitar também a automatização do projeto.
Qual API utilizaremos para os testes? Por qual motivo?
Postar também:
* Link para  API
* Link para a documentação para a API

Ao ser definido esse tópico devemos criar a task no Projects para:
* Implementação da API no Gradle
* Documentação de como deve ser os testes
* Um exemplo de teste

**Comment by LorenzooG** [comment]
O projeto jetbrains annotations é muito útil para tooling e facilita o interop com kotlin.

[Source code](https://github.com/JetBrains/java-annotations) e ["Documentação"](https://www.jetbrains.com/help/idea/annotating-source-code.html#bundled-annotations)

**Comment by DevNatan** [comment]
https://github.com/kotest/kotest
https://kotest.io/docs/quickstart

**Comment by luigieai** [comment]
A questão é: Utilizaremos Java ou Kotlin no projeto? Assim que for decidido podemos sim considerar o Kotest, parece um projeto estável.

**Comment by aripiprazole** [comment]
> A questão é: Utilizaremos Java ou Kotlin no projeto? Assim que for decidido podemos sim considerar o Kotest, parece um projeto estável.

Eu particularmente gosto muito do Kotest, é muito versátil, tem vários meios de fazer testes, suporte para vários specs: (link)[https://kotest.io/docs/framework/testing-styles.html]. Além de ser multiplatform, creio que seja uma boa opção.

**Comment by mtbarr** [comment]
> A questão é: Utilizaremos Java ou Kotlin no projeto? Assim que for decidido podemos sim considerar o Kotest, parece um projeto estável.

A linguagem de programação já foi definida na issue: https://github.com/Techbox-Project/techbox/issues/5 

Quanto a framework de testes, utilizaremos Kotest no momento, é um projeto estavel e nossos desenvolvedores já tem uma certa experiência com ele. Obrigado pela pergunta! :smile:
