### ISSUE TITLE
Qual linguagem de programação será utilizada?

### ISSUE THREAD

**Issue by luigieai** [Techbox-Project/techbox#5]
Olá!
No momento estamos em debate interno em quais linguagens de programação iremos utilizar no projeto! 

Essa issue será para oficializar qual linguagem utilizaremos.

**Comment by DevNatan** [comment]
Kotlin, vantagens:
- kotlinx.atomicfu - features do Java 9 no Java 8
- kotlinx.io - quem quiser se aventurar com networking
- exposed - framework SQL, com 1 classe e 2 linha vc ja cria uma base da dados
- kotlinx.scripting - scripting, criar os comandos usando arquivos .kts em vez de editar a source (tipo os de JavaScript)
- [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) - garantir que concurrency funcione mesmo pra quem não entende absolutamente nada e ser possível dar switch entre multiplas threads qnd quiser a hora q quiser onde quiser
- Kotlin em sí: extremamente funcional, tem extensions, é possível criação de comandos inline ex `command("abc") { ... }`

Java, vantagens:
- Todo mundo sabe
- Tem frameworks (ex.: JDA) prontas para uso

**Comment by mtbarr** [comment]
No momento utilizaremos Kotlin por todos os motivos que o nosso amigo @DevNatan citou acima, então acredito que esta questão já possa ser considerada respondida. Obrigado pela sua pergunta! :smile:
